labels: ["EMPv2-support"]
body:
  - type: input
    id: question
    attributes:
      label: Which tenant are you representing?
      description: please specify the tenant folder name
    validations:
      required: true 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@maersk.com
    validations:
      required: true
  - type: dropdown
    id: Environment
    attributes:
      label: Select the environment (Pre-Prod or Production) in which the issue exists.
      options:
        - Pre-Prod
        - Production
    validations:
      required: true
  - type: input
    id: topic
    attributes:
      label: What is the name of topic/Consumer/Connector you are having issues with?
      description: Mention the Kafka Component you have issues with.
    validations:
      required: true
  - type: dropdown
    id: question
    attributes:
      label: Are you accessing the topic in Ground (OnPrem) or in the Cloud?
      description: Where are you accessing the topic.
      options:
        - Ground-OnPrem 
        - Cloud
    validations:
      required: true
  - type: dropdown
    id: question
    attributes:
      label: Are you experiencing an issue consuming (reading) or producing (writing) to a topic?
      description: Problem with Producing/Consuming.
      options:
        - Producing 
        - Consuming
    validations:
      required: true
  - type: input
    id: question
    attributes:
      label: What is the name of the user you are using to access the topic?
      description: Please mention the username only 
    validations:
      required: true
  - type: input
    id: question
    attributes:
      label: What consumer group name are you using (if reading from topics)?
      description: Please mention the Consumer Group name 
    validations:
      required: false
  - type: textarea
    id: issue
    attributes:
      label: What actually happened. It's important to include any error messages or screenshots
      description: Explain the issue in detail.
      render: shell
    validations:
      required: true
